name: Create Comic Book Release
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Comic Book Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        path: 'ComicbookVFX'
        type: 'zip'
        filename: 'ComicbookVFX.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig *.yml'
